### ISSUE TITLE
[bug] Can't remove Mekanism Metallurgic Infuser recipes

### ISSUE THREAD

**Issue by Kataiser9** [jaredlll08/ModTweaker2#91] opened 2015-03-14 05:45 UTC
Relevant part of the MT log: http://pastebin.com/65ELNuA1

Looks like the input and output objects are reversed or something? At any rate, checking the affected recipe will either show that it isn't properly removed (if you haven't reloaded scripts in the current session) or just crash the game (if you have). Crash log: http://pastebin.com/eDGCX3Kk

**Comment by Sweety42** [comment] 2015-03-16 09:46
I got trouble too with the metallurgic infuser since 0.7.2,
between 0.7.2 and 0.7.4 the script just dont work but with the 0.7.5 it crash the client

**Comment by Bunsan** [comment] 2015-04-08 08:33
I commented on this in issue #102 The problem is that the Mekanism API has changed and ModTweaker is referencing classes that no longer exist. Specifically 
import mekanism.api.infuse.InfusionInput;
import mekanism.api.infuse.InfusionOutput;

**Comment by Zixxl** [comment] 2015-07-15 09:55
Fixed in ModTweaker2 0.9.0. Please update! (Also update Mekanism to v8)

**Closed** 2015-07-15 09:56 UTC
Labels: bug, mekanism
