### ISSUE TITLE
[Suggestion][1.7.10][Thaumcraft 4] Add a way to lock research behind specific items being scanned

### ISSUE THREAD

**Issue by filloax** [jaredlll08/ModTweaker2#312] opened 2016-03-10 19:42 UTC
Like brain in a jar

**Comment by Yulife** [comment] 2016-03-24 12:55
Duplicate of https://github.com/jaredlll08/ModTweaker2/issues/212. Jared can you look into it though? :s

**Closed by Yulife** 2016-03-24 12:55 UTC
