### ISSUE TITLE
ERROR: Error executing <file>.zs: mekanism/api/infuse/InfusionInput or InfusionOutput

### ISSUE THREAD

**Issue by qqii** [jaredlll08/ModTweaker2#111] opened 2015-04-10 04:41 UTC
![2015-04-10_05 16 01](https://cloud.githubusercontent.com/assets/6891353/7081826/b3b30b8c-df40-11e4-9e91-4fd4fe7f35e1.png)
The code used was from the [wiki](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Mekanism_Support):
mods.mekanism.Infuser.removeRecipe(<minecraft:mossy_cobblestone>);

This is because of [Infuser.java](https://github.com/joshiejack/ModTweaker/blob/master/src/main/java/modtweaker/mods/mekanism/handlers/Infuser.java) which uses mekanism.api.infuse.InfusionInput and mekanism.api.infuse.InfusionOutput. [This no longer exists.](https://github.com/aidancbrady/Mekanism/tree/master/src/main/java/mekanism/api/infuse) 
It seems to have been replaced by [RecipeHelper.java](https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/api/recipe/RecipeHelper.java). Unfortunately according to the comment, this is going to be removed in the next update. The [mekanism wiki page](https://github.com/aidancbrady/Mekanism/wiki/IMC-based-recipe-integration) talks about the replacement, IMC based integration.

The sawmill also seems to have had changes as ![image](http://puu.sh/h8arT/e4eb4fc975.png) occurs when trying to remove a recipe from the sawmill. 
The code used was also from the wiki:
mods.mekanism.Sawmill.removeRecipe(<minecraft:fence>);

Here is a link to [ItemStackInput.java](https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/recipe/inputs/ItemStackInput.java).

**Comment by joshiejack** [comment] 2015-04-10 04:44
IMC is not even an option for anything with modtweaker btw. IMC happens too early.

**Comment by QQII** [comment] 2015-04-10 04:51
Sorry, I'm not very familiar with forge. It looks like the maintainers will have to talk with the mekanism devs to sort something out then.

**Comment by skaviouz** [comment] 2015-04-16 00:56
possible duplicate of #91
confirmed bug w/ mekanism 8.1.1.225

**Comment by Maxwelljones** [comment] 2015-05-05 12:30
Sorry is there any option for a solution coming up? Not sure how I should handle this on the modpack end. Not willing to give any pressure, just would like to get an information about how this could be handled :) thanks!

**Comment by Zixxl** [comment] 2015-07-15 09:55
Fixed in ModTweaker2 0.9.0. Please update!

**Closed by Zixxl** 2015-07-15 09:55 UTC
Labels: bug, mekanism
