### ISSUE TITLE
AE2 Support broken in rv2.beta build 28

### ISSUE THREAD

**Issue by JAWSAWN** [jaredlll08/ModTweaker2#116] opened 2015-04-17 22:23 UTC
The scripts I wrote with rv2.beta build 18 for press does no longer work in rv2.beta build 28. I assume some code changed in ae2?

**Comment by Yulife** [comment] 2015-04-18 08:49
Duplicate of https://github.com/jaredlll08/ModTweaker2/issues/110.

**Closed by Yulife** 2015-04-18 08:49 UTC
