### ISSUE TITLE
Don`t work BlastFurnace - remove Fuel

### ISSUE THREAD

**Issue by Tsyklop** [jaredlll08/ModTweaker2#248] opened 2015-09-26 12:23 UTC
![2015-09-26_15 21 17](https://cloud.githubusercontent.com/assets/6783568/10117524/8b17564a-6462-11e5-9d27-aecb406d96a1.png)

**Comment by Voidi** [comment] 2015-09-26 12:45
How about a bit more information?
Versions of coherently mods, your Script file oh and minetweaker has a own log file, you don't have Screenshot the error messages.

**Comment by Tsyklop** [comment] 2015-09-26 12:53
Railcraft_1.7.10-9.7.0.0, ModTweaker2-0.9.3/

Script:
`mods.railcraft.BlastFurnace.removeFuel(<minecraft:coal:1>);`

**Comment by Yulife** [comment] 2015-09-26 13:17
Duplicate of #193.

**Closed by Yulife** 2015-09-26 13:17 UTC
