### ISSUE TITLE
[Suggestion] Add support for GalactiCraft

### ISSUE THREAD

**Issue by Tsyklop** [jaredlll08/ModTweaker2#247] opened 2015-09-25 21:25 UTC
Pls add support GalactiCraft...

**Comment by Yulife** [comment] 2015-09-25 21:30
Duplicate of #219. Please go through the existing issues before making a new one.

**Closed by Yulife** 2015-09-25 21:30 UTC

**Comment by Tsyklop** [comment] 2015-09-25 21:49
I'm talking about all the mechanisms of mod not just Workbench.
