### ISSUE TITLE
Ex Nihilio

### ISSUE THREAD

**Issue by Mattabase** [jaredlll08/ModTweaker2#172] opened 2015-07-06 11:17 UTC
https://dl.dropboxusercontent.com/u/15990261/ShareX/2015/07/2015-07-06_07-15-34.png

When trying remove a Sieve Recipe 

mods.exnihilo.Sieve.removeRecipe(<minecraft:wheat_seeds>);

Command used

**Comment by Zixxl** [comment] 2015-07-06 11:47
You need to provide both input and output to remove a recipe:

```mods.exnihilo.Sieve.removeRecipe(Input, Output);```

**Comment by jaredlll08** [comment] 2015-07-07 16:13
Close
(No idea if the works)
I know this is fixed

**Comment by hephinator** [comment] 2015-07-08 08:11
Can confirm. This (and a whole slew of other ExNihilo bugs) was fixed in 0.8.2.

Jared, like every other programmer on the planet, is terrible at updating documentation while adding new features / changing things.

If you are unsure, run ModTweaker through a decompiler and look for mods.exnihilo.handlers.Sieve.removeRecipe() it calls for two IItemStacks to be passed into it, first is input, second is output. This was changed due to changes on ExNihilo's end when computing rewards. Go yell at @mikelydeamore for messing it all up >:) Kappa

**Comment by jaredlll08** [comment] 2015-07-08 08:21
Actually, @yulife does documentation, not me, so go shout at him! >.> <.<

**Comment by Zixxl** [comment] 2015-07-08 14:41
This is a documentation issue not a bug in ModTweaker2. I'll close this issue.

**Comment by Yulife** [comment] 2015-07-11 16:27
I'm on vacation you dork, you do it ;) (or Snowshock)

**Comment by Yulife** [comment] 2015-07-11 16:28
Documentation is important so this will stay open until the doc is fixed :thumbsup:

**Comment by Zixxl** [comment] 2015-07-14 12:19
Changed the function a little for the next version:
```mods.exnihilo.Sieve.removeRecipe(Input, @Optional Output);```

To remove ```<minecraft:wheat_seeds>``` from all recipes, the command would be:

```mods.exnihilo.Sieve.removeRecipe(<*>, <minecraft:wheat_seeds>);```

**Comment by Zixxl** [comment] 2015-07-17 07:30
Wiki updated

**Closed by Zixxl** 2015-07-17 07:30 UTC
Labels: exnihilo
